/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_SLASH = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_ATimport = 3,
  sym_to_eol = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_AT_LPAREN = 7,
  aux_sym_block_embed_token1 = 8,
  anon_sym_RPAREN = 9,
  aux_sym_block_contents_token1 = 10,
  anon_sym_source_SLASH = 11,
  anon_sym_target_SLASH = 12,
  anon_sym_host_SLASH = 13,
  anon_sym_image_SLASH = 14,
  anon_sym_LBRACK = 15,
  anon_sym_RBRACK = 16,
  sym_recipe_name = 17,
  anon_sym_url = 18,
  anon_sym_COLON = 19,
  anon_sym_type = 20,
  anon_sym_tar_DOTgz = 21,
  anon_sym_tar_DOTxz = 22,
  anon_sym_git = 23,
  anon_sym_local = 24,
  anon_sym_patch = 25,
  anon_sym_b2sum = 26,
  anon_sym_commit = 27,
  anon_sym_dependencies = 28,
  anon_sym_strap = 29,
  anon_sym_source = 30,
  anon_sym_configure = 31,
  anon_sym_build = 32,
  anon_sym_install = 33,
  sym_source_file = 34,
  sym_comment = 35,
  sym_directives = 36,
  sym_import_directive = 37,
  sym_block = 38,
  sym_block_embed = 39,
  sym_block_contents = 40,
  sym_dependency = 41,
  sym_dependencies = 42,
  sym_recipe = 43,
  sym_source_rules = 44,
  sym_source_rule = 45,
  sym_common_rules = 46,
  sym_common_rule = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_block_contents_repeat1 = 49,
  aux_sym_dependencies_repeat1 = 50,
  aux_sym_source_rules_repeat1 = 51,
  aux_sym_common_rules_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_ATimport] = "@import",
  [sym_to_eol] = "to_eol",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_AT_LPAREN] = "@(",
  [aux_sym_block_embed_token1] = "block_embed_token1",
  [anon_sym_RPAREN] = ")",
  [aux_sym_block_contents_token1] = "block_contents_token1",
  [anon_sym_source_SLASH] = "source/",
  [anon_sym_target_SLASH] = "target/",
  [anon_sym_host_SLASH] = "host/",
  [anon_sym_image_SLASH] = "image/",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_recipe_name] = "recipe_name",
  [anon_sym_url] = "url",
  [anon_sym_COLON] = ":",
  [anon_sym_type] = "type",
  [anon_sym_tar_DOTgz] = "tar.gz",
  [anon_sym_tar_DOTxz] = "tar.xz",
  [anon_sym_git] = "git",
  [anon_sym_local] = "local",
  [anon_sym_patch] = "patch",
  [anon_sym_b2sum] = "b2sum",
  [anon_sym_commit] = "commit",
  [anon_sym_dependencies] = "dependencies",
  [anon_sym_strap] = "strap",
  [anon_sym_source] = "source",
  [anon_sym_configure] = "configure",
  [anon_sym_build] = "build",
  [anon_sym_install] = "install",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_directives] = "directives",
  [sym_import_directive] = "import_directive",
  [sym_block] = "block",
  [sym_block_embed] = "block_embed",
  [sym_block_contents] = "block_contents",
  [sym_dependency] = "dependency",
  [sym_dependencies] = "dependencies",
  [sym_recipe] = "recipe",
  [sym_source_rules] = "source_rules",
  [sym_source_rule] = "source_rule",
  [sym_common_rules] = "common_rules",
  [sym_common_rule] = "common_rule",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_contents_repeat1] = "block_contents_repeat1",
  [aux_sym_dependencies_repeat1] = "dependencies_repeat1",
  [aux_sym_source_rules_repeat1] = "source_rules_repeat1",
  [aux_sym_common_rules_repeat1] = "common_rules_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_ATimport] = anon_sym_ATimport,
  [sym_to_eol] = sym_to_eol,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_AT_LPAREN] = anon_sym_AT_LPAREN,
  [aux_sym_block_embed_token1] = aux_sym_block_embed_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_block_contents_token1] = aux_sym_block_contents_token1,
  [anon_sym_source_SLASH] = anon_sym_source_SLASH,
  [anon_sym_target_SLASH] = anon_sym_target_SLASH,
  [anon_sym_host_SLASH] = anon_sym_host_SLASH,
  [anon_sym_image_SLASH] = anon_sym_image_SLASH,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_recipe_name] = sym_recipe_name,
  [anon_sym_url] = anon_sym_url,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_tar_DOTgz] = anon_sym_tar_DOTgz,
  [anon_sym_tar_DOTxz] = anon_sym_tar_DOTxz,
  [anon_sym_git] = anon_sym_git,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_patch] = anon_sym_patch,
  [anon_sym_b2sum] = anon_sym_b2sum,
  [anon_sym_commit] = anon_sym_commit,
  [anon_sym_dependencies] = anon_sym_dependencies,
  [anon_sym_strap] = anon_sym_strap,
  [anon_sym_source] = anon_sym_source,
  [anon_sym_configure] = anon_sym_configure,
  [anon_sym_build] = anon_sym_build,
  [anon_sym_install] = anon_sym_install,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_directives] = sym_directives,
  [sym_import_directive] = sym_import_directive,
  [sym_block] = sym_block,
  [sym_block_embed] = sym_block_embed,
  [sym_block_contents] = sym_block_contents,
  [sym_dependency] = sym_dependency,
  [sym_dependencies] = sym_dependencies,
  [sym_recipe] = sym_recipe,
  [sym_source_rules] = sym_source_rules,
  [sym_source_rule] = sym_source_rule,
  [sym_common_rules] = sym_common_rules,
  [sym_common_rule] = sym_common_rule,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_contents_repeat1] = aux_sym_block_contents_repeat1,
  [aux_sym_dependencies_repeat1] = aux_sym_dependencies_repeat1,
  [aux_sym_source_rules_repeat1] = aux_sym_source_rules_repeat1,
  [aux_sym_common_rules_repeat1] = aux_sym_common_rules_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_ATimport] = {
    .visible = true,
    .named = false,
  },
  [sym_to_eol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_embed_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_contents_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_source_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_target_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_host_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_image_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_recipe_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_url] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tar_DOTgz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tar_DOTxz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_git] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_patch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b2sum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_commit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dependencies] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_strap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_source] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_configure] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_build] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_install] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_directives] = {
    .visible = true,
    .named = true,
  },
  [sym_import_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_embed] = {
    .visible = true,
    .named = true,
  },
  [sym_block_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency] = {
    .visible = true,
    .named = true,
  },
  [sym_dependencies] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [sym_source_rules] = {
    .visible = true,
    .named = true,
  },
  [sym_source_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_common_rules] = {
    .visible = true,
    .named = true,
  },
  [sym_common_rule] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_contents_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dependencies_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_rules_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_common_rules_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(105);
      ADVANCE_MAP(
        ')', 119,
        '/', 4,
        ':', 131,
        '@', 2,
        '[', 127,
        ']', 128,
        'b', 9,
        'c', 66,
        'd', 27,
        'g', 45,
        'h', 67,
        'i', 57,
        'l', 64,
        'p', 12,
        's', 65,
        't', 13,
        'u', 75,
        '{', 114,
        '}', 115,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(110);
      if (lookahead == '\\') ADVANCE(107);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(116);
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(106);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(125);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(126);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(123);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(124);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(85);
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 10:
      if (lookahead == '@') ADVANCE(121);
      if (lookahead == '{') ADVANCE(114);
      if (lookahead == '}') ADVANCE(115);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0) ADVANCE(120);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == 'y') ADVANCE(73);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(81);
      END_STATE();
    case 18:
      ADVANCE_MAP(
        'b', 9,
        'c', 66,
        'd', 27,
        'i', 63,
        'p', 12,
        's', 70,
        't', 100,
        'u', 75,
        '}', 115,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'd') ADVANCE(145);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(143);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(144);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(142);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'f') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'g') ADVANCE(101);
      if (lookahead == 'x') ADVANCE(102);
      END_STATE();
    case 40:
      if (lookahead == 'g') ADVANCE(34);
      END_STATE();
    case 41:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 42:
      if (lookahead == 'g') ADVANCE(97);
      END_STATE();
    case 43:
      if (lookahead == 'h') ADVANCE(137);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(88);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(89);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(130);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(136);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(146);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 55:
      if (lookahead == 'm') ADVANCE(138);
      END_STATE();
    case 56:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 57:
      if (lookahead == 'm') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(87);
      END_STATE();
    case 58:
      if (lookahead == 'm') ADVANCE(60);
      if (lookahead == 'n') ADVANCE(38);
      END_STATE();
    case 59:
      if (lookahead == 'm') ADVANCE(74);
      END_STATE();
    case 60:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(87);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(96);
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 66:
      if (lookahead == 'o') ADVANCE(58);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(86);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(98);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(99);
      if (lookahead == 't') ADVANCE(78);
      END_STATE();
    case 71:
      if (lookahead == 'p') ADVANCE(141);
      END_STATE();
    case 72:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(68);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(90);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 82:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 83:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 84:
      if (lookahead == 's') ADVANCE(140);
      END_STATE();
    case 85:
      if (lookahead == 's') ADVANCE(95);
      END_STATE();
    case 86:
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(94);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(135);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(139);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 95:
      if (lookahead == 'u') ADVANCE(55);
      END_STATE();
    case 96:
      if (lookahead == 'u') ADVANCE(77);
      END_STATE();
    case 97:
      if (lookahead == 'u') ADVANCE(80);
      END_STATE();
    case 98:
      if (lookahead == 'u') ADVANCE(82);
      END_STATE();
    case 99:
      if (lookahead == 'u') ADVANCE(83);
      END_STATE();
    case 100:
      if (lookahead == 'y') ADVANCE(73);
      END_STATE();
    case 101:
      if (lookahead == 'z') ADVANCE(133);
      END_STATE();
    case 102:
      if (lookahead == 'z') ADVANCE(134);
      END_STATE();
    case 103:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(103);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 104:
      if (eof) ADVANCE(105);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '@') ADVANCE(44);
      if (lookahead == ']') ADVANCE(128);
      if (lookahead == 'h') ADVANCE(67);
      if (lookahead == 'i') ADVANCE(56);
      if (lookahead == 's') ADVANCE(69);
      if (lookahead == 't') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(110);
      if (lookahead == '\\') ADVANCE(107);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(109);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_ATimport);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_to_eol);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(113);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_to_eol);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_AT_LPAREN);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_block_embed_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_block_embed_token1);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_block_contents_token1);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_block_contents_token1);
      if (lookahead == '(') ADVANCE(116);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_block_contents_token1);
      if (lookahead == '@') ADVANCE(121);
      if (lookahead == '{') ADVANCE(114);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(120);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_source_SLASH);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_target_SLASH);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_host_SLASH);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_image_SLASH);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_recipe_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(129);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_url);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_tar_DOTgz);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_tar_DOTxz);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_git);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_patch);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_b2sum);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_commit);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_dependencies);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_strap);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_source);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_source);
      if (lookahead == '/') ADVANCE(123);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_configure);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_build);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_install);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 104},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 104},
  [7] = {.lex_state = 104},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 104},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 104},
  [19] = {.lex_state = 104},
  [20] = {.lex_state = 104},
  [21] = {.lex_state = 104},
  [22] = {.lex_state = 104},
  [23] = {.lex_state = 104},
  [24] = {.lex_state = 104},
  [25] = {.lex_state = 104},
  [26] = {.lex_state = 104},
  [27] = {.lex_state = 104},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 104},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 103},
  [44] = {.lex_state = 103},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 117},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 112},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 108},
  [53] = {.lex_state = 112},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 103},
  [57] = {.lex_state = 103},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_ATimport] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_AT_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_source_SLASH] = ACTIONS(1),
    [anon_sym_target_SLASH] = ACTIONS(1),
    [anon_sym_host_SLASH] = ACTIONS(1),
    [anon_sym_image_SLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_url] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_tar_DOTgz] = ACTIONS(1),
    [anon_sym_tar_DOTxz] = ACTIONS(1),
    [anon_sym_git] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_patch] = ACTIONS(1),
    [anon_sym_b2sum] = ACTIONS(1),
    [anon_sym_commit] = ACTIONS(1),
    [anon_sym_dependencies] = ACTIONS(1),
    [anon_sym_strap] = ACTIONS(1),
    [anon_sym_source] = ACTIONS(1),
    [anon_sym_configure] = ACTIONS(1),
    [anon_sym_build] = ACTIONS(1),
    [anon_sym_install] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(49),
    [sym_comment] = STATE(7),
    [sym_directives] = STATE(7),
    [sym_import_directive] = STATE(25),
    [sym_recipe] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH_SLASH] = ACTIONS(5),
    [anon_sym_ATimport] = ACTIONS(7),
    [anon_sym_source_SLASH] = ACTIONS(9),
    [anon_sym_target_SLASH] = ACTIONS(11),
    [anon_sym_host_SLASH] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(13), 12,
      anon_sym_RBRACE,
      anon_sym_url,
      anon_sym_type,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
      anon_sym_dependencies,
      anon_sym_strap,
      anon_sym_source,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [15] = 1,
    ACTIONS(15), 12,
      anon_sym_RBRACE,
      anon_sym_url,
      anon_sym_type,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
      anon_sym_dependencies,
      anon_sym_strap,
      anon_sym_source,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [30] = 1,
    ACTIONS(17), 12,
      anon_sym_RBRACE,
      anon_sym_url,
      anon_sym_type,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
      anon_sym_dependencies,
      anon_sym_strap,
      anon_sym_source,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [45] = 1,
    ACTIONS(19), 12,
      anon_sym_RBRACE,
      anon_sym_url,
      anon_sym_type,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
      anon_sym_dependencies,
      anon_sym_strap,
      anon_sym_source,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [60] = 7,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(26), 1,
      anon_sym_ATimport,
    ACTIONS(29), 1,
      anon_sym_source_SLASH,
    STATE(25), 1,
      sym_import_directive,
    ACTIONS(32), 2,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
    STATE(6), 4,
      sym_comment,
      sym_directives,
      sym_recipe,
      aux_sym_source_file_repeat1,
  [86] = 7,
    ACTIONS(5), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      anon_sym_ATimport,
    ACTIONS(9), 1,
      anon_sym_source_SLASH,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_import_directive,
    ACTIONS(11), 2,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
    STATE(6), 4,
      sym_comment,
      sym_directives,
      sym_recipe,
      aux_sym_source_file_repeat1,
  [112] = 6,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      anon_sym_dependencies,
    ACTIONS(45), 1,
      anon_sym_strap,
    STATE(9), 2,
      sym_source_rule,
      aux_sym_source_rules_repeat1,
    ACTIONS(39), 4,
      anon_sym_url,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
  [135] = 6,
    ACTIONS(41), 1,
      anon_sym_type,
    ACTIONS(43), 1,
      anon_sym_dependencies,
    ACTIONS(45), 1,
      anon_sym_strap,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(10), 2,
      sym_source_rule,
      aux_sym_source_rules_repeat1,
    ACTIONS(39), 4,
      anon_sym_url,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
  [158] = 6,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(54), 1,
      anon_sym_type,
    ACTIONS(57), 1,
      anon_sym_dependencies,
    ACTIONS(60), 1,
      anon_sym_strap,
    STATE(10), 2,
      sym_source_rule,
      aux_sym_source_rules_repeat1,
    ACTIONS(51), 4,
      anon_sym_url,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
  [181] = 5,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      anon_sym_dependencies,
    ACTIONS(67), 1,
      anon_sym_source,
    STATE(14), 2,
      sym_common_rule,
      aux_sym_common_rules_repeat1,
    ACTIONS(69), 3,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [200] = 1,
    ACTIONS(71), 8,
      anon_sym_RBRACE,
      anon_sym_url,
      anon_sym_type,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
      anon_sym_dependencies,
      anon_sym_strap,
  [211] = 5,
    ACTIONS(65), 1,
      anon_sym_dependencies,
    ACTIONS(67), 1,
      anon_sym_source,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(11), 2,
      sym_common_rule,
      aux_sym_common_rules_repeat1,
    ACTIONS(69), 3,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [230] = 5,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(77), 1,
      anon_sym_dependencies,
    ACTIONS(80), 1,
      anon_sym_source,
    STATE(14), 2,
      sym_common_rule,
      aux_sym_common_rules_repeat1,
    ACTIONS(83), 3,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [249] = 1,
    ACTIONS(86), 8,
      anon_sym_RBRACE,
      anon_sym_url,
      anon_sym_type,
      anon_sym_patch,
      anon_sym_b2sum,
      anon_sym_commit,
      anon_sym_dependencies,
      anon_sym_strap,
  [260] = 3,
    ACTIONS(90), 1,
      anon_sym_RBRACK,
    STATE(18), 2,
      sym_dependency,
      aux_sym_dependencies_repeat1,
    ACTIONS(88), 4,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
      anon_sym_image_SLASH,
  [274] = 6,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      anon_sym_AT_LPAREN,
    ACTIONS(98), 1,
      aux_sym_block_contents_token1,
    STATE(51), 1,
      sym_block_contents,
    STATE(29), 2,
      sym_block_embed,
      aux_sym_block_contents_repeat1,
  [294] = 3,
    ACTIONS(100), 1,
      anon_sym_RBRACK,
    STATE(19), 2,
      sym_dependency,
      aux_sym_dependencies_repeat1,
    ACTIONS(88), 4,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
      anon_sym_image_SLASH,
  [308] = 3,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    STATE(19), 2,
      sym_dependency,
      aux_sym_dependencies_repeat1,
    ACTIONS(102), 4,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
      anon_sym_image_SLASH,
  [322] = 1,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [331] = 1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [340] = 1,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [349] = 1,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [358] = 1,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [367] = 1,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [376] = 1,
    ACTIONS(119), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [385] = 1,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_ATimport,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
  [394] = 1,
    ACTIONS(123), 6,
      anon_sym_RBRACE,
      anon_sym_dependencies,
      anon_sym_source,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [403] = 5,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_AT_LPAREN,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 1,
      aux_sym_block_contents_token1,
    STATE(32), 2,
      sym_block_embed,
      aux_sym_block_contents_repeat1,
  [420] = 5,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_AT_LPAREN,
    ACTIONS(98), 1,
      aux_sym_block_contents_token1,
    STATE(54), 1,
      sym_block_contents,
    STATE(29), 2,
      sym_block_embed,
      aux_sym_block_contents_repeat1,
  [437] = 1,
    ACTIONS(129), 6,
      anon_sym_RBRACE,
      anon_sym_dependencies,
      anon_sym_source,
      anon_sym_configure,
      anon_sym_build,
      anon_sym_install,
  [446] = 5,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      anon_sym_AT_LPAREN,
    ACTIONS(139), 1,
      aux_sym_block_contents_token1,
    STATE(32), 2,
      sym_block_embed,
      aux_sym_block_contents_repeat1,
  [463] = 1,
    ACTIONS(142), 5,
      anon_sym_source_SLASH,
      anon_sym_target_SLASH,
      anon_sym_host_SLASH,
      anon_sym_image_SLASH,
      anon_sym_RBRACK,
  [471] = 1,
    ACTIONS(144), 4,
      anon_sym_tar_DOTgz,
      anon_sym_tar_DOTxz,
      anon_sym_git,
      anon_sym_local,
  [478] = 1,
    ACTIONS(146), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT_LPAREN,
      aux_sym_block_contents_token1,
  [485] = 1,
    ACTIONS(148), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT_LPAREN,
      aux_sym_block_contents_token1,
  [492] = 2,
    ACTIONS(150), 1,
      anon_sym_LBRACK,
    STATE(12), 1,
      sym_dependencies,
  [499] = 2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_common_rules,
  [506] = 2,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_source_rules,
  [513] = 2,
    ACTIONS(150), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym_dependencies,
  [520] = 2,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
  [527] = 2,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [534] = 1,
    ACTIONS(158), 1,
      sym_recipe_name,
  [538] = 1,
    ACTIONS(160), 1,
      sym_recipe_name,
  [542] = 1,
    ACTIONS(162), 1,
      anon_sym_COLON,
  [546] = 1,
    ACTIONS(164), 1,
      anon_sym_COLON,
  [550] = 1,
    ACTIONS(166), 1,
      anon_sym_COLON,
  [554] = 1,
    ACTIONS(168), 1,
      aux_sym_block_embed_token1,
  [558] = 1,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
  [562] = 1,
    ACTIONS(144), 1,
      sym_to_eol,
  [566] = 1,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
  [570] = 1,
    ACTIONS(174), 1,
      aux_sym_comment_token1,
  [574] = 1,
    ACTIONS(176), 1,
      sym_to_eol,
  [578] = 1,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
  [582] = 1,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
  [586] = 1,
    ACTIONS(182), 1,
      sym_recipe_name,
  [590] = 1,
    ACTIONS(184), 1,
      sym_recipe_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 45,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 86,
  [SMALL_STATE(8)] = 112,
  [SMALL_STATE(9)] = 135,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 181,
  [SMALL_STATE(12)] = 200,
  [SMALL_STATE(13)] = 211,
  [SMALL_STATE(14)] = 230,
  [SMALL_STATE(15)] = 249,
  [SMALL_STATE(16)] = 260,
  [SMALL_STATE(17)] = 274,
  [SMALL_STATE(18)] = 294,
  [SMALL_STATE(19)] = 308,
  [SMALL_STATE(20)] = 322,
  [SMALL_STATE(21)] = 331,
  [SMALL_STATE(22)] = 340,
  [SMALL_STATE(23)] = 349,
  [SMALL_STATE(24)] = 358,
  [SMALL_STATE(25)] = 367,
  [SMALL_STATE(26)] = 376,
  [SMALL_STATE(27)] = 385,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 403,
  [SMALL_STATE(30)] = 420,
  [SMALL_STATE(31)] = 437,
  [SMALL_STATE(32)] = 446,
  [SMALL_STATE(33)] = 463,
  [SMALL_STATE(34)] = 471,
  [SMALL_STATE(35)] = 478,
  [SMALL_STATE(36)] = 485,
  [SMALL_STATE(37)] = 492,
  [SMALL_STATE(38)] = 499,
  [SMALL_STATE(39)] = 506,
  [SMALL_STATE(40)] = 513,
  [SMALL_STATE(41)] = 520,
  [SMALL_STATE(42)] = 527,
  [SMALL_STATE(43)] = 534,
  [SMALL_STATE(44)] = 538,
  [SMALL_STATE(45)] = 542,
  [SMALL_STATE(46)] = 546,
  [SMALL_STATE(47)] = 550,
  [SMALL_STATE(48)] = 554,
  [SMALL_STATE(49)] = 558,
  [SMALL_STATE(50)] = 562,
  [SMALL_STATE(51)] = 566,
  [SMALL_STATE(52)] = 570,
  [SMALL_STATE(53)] = 574,
  [SMALL_STATE(54)] = 578,
  [SMALL_STATE(55)] = 582,
  [SMALL_STATE(56)] = 586,
  [SMALL_STATE(57)] = 590,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependencies, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependencies, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_rules_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_rule, 2, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_common_rules_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_common_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_common_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_common_rules_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_rule, 3, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dependencies_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dependencies_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_directive, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_rules, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_common_rules, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directives, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_rules, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_common_rules, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_common_rule, 2, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_contents, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_common_rule, 3, 0, 1),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_contents_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_contents_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_contents_repeat1, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_embed, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [170] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chariot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "chariot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
