/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 1
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_SLASH = 1,
  aux_sym_comment_token1 = 2,
  sym_tok_identifier = 3,
  sym_tok_string = 4,
  anon_sym_LT = 5,
  aux_sym_tok_code_block_token1 = 6,
  anon_sym_GT = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_LBRACE = 10,
  anon_sym_COLON = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACE = 13,
  anon_sym_LBRACK = 14,
  anon_sym_RBRACK = 15,
  sym_close_tag = 16,
  sym_code = 17,
  sym_error_sentinel = 18,
  sym_source_file = 19,
  sym_comment = 20,
  sym_tok_code_block = 21,
  sym_fragment = 22,
  sym_string = 23,
  sym_code_block = 24,
  sym_recipe_ref = 25,
  sym_object = 26,
  sym_list = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_tok_code_block_repeat1 = 29,
  aux_sym_object_repeat1 = 30,
  aux_sym_list_repeat1 = 31,
  alias_sym_content = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_tok_identifier] = "tok_identifier",
  [sym_tok_string] = "tok_string",
  [anon_sym_LT] = "<",
  [aux_sym_tok_code_block_token1] = "lang",
  [anon_sym_GT] = ">",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_close_tag] = "close_tag",
  [sym_code] = "code",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_tok_code_block] = "tok_code_block",
  [sym_fragment] = "fragment",
  [sym_string] = "string",
  [sym_code_block] = "code_block",
  [sym_recipe_ref] = "recipe_ref",
  [sym_object] = "object",
  [sym_list] = "list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tok_code_block_repeat1] = "tok_code_block_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [alias_sym_content] = "content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_tok_identifier] = sym_tok_identifier,
  [sym_tok_string] = sym_tok_string,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_tok_code_block_token1] = aux_sym_tok_code_block_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_close_tag] = sym_close_tag,
  [sym_code] = sym_code,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_tok_code_block] = sym_tok_code_block,
  [sym_fragment] = sym_fragment,
  [sym_string] = sym_string,
  [sym_code_block] = sym_code_block,
  [sym_recipe_ref] = sym_recipe_ref,
  [sym_object] = sym_object,
  [sym_list] = sym_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tok_code_block_repeat1] = aux_sym_tok_code_block_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [alias_sym_content] = alias_sym_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tok_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_tok_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tok_code_block_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tok_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tok_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [3] = alias_sym_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_tok_code_block_repeat1, 2,
    aux_sym_tok_code_block_repeat1,
    alias_sym_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 2,
        '*', 16,
        ',', 20,
        '/', 17,
        ':', 19,
        '<', 13,
        '>', 15,
        '[', 22,
        ']', 23,
        '{', 18,
        '}', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_tok_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_tok_string);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_tok_code_block_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(4);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 14},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_tok_identifier] = ACTIONS(1),
    [sym_tok_string] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_close_tag] = ACTIONS(1),
    [sym_code] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym_comment] = STATE(1),
    [sym_recipe_ref] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_tok_identifier] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_comment] = STATE(2),
    [sym_tok_code_block] = STATE(13),
    [sym_fragment] = STATE(17),
    [sym_string] = STATE(14),
    [sym_code_block] = STATE(14),
    [sym_recipe_ref] = STATE(14),
    [sym_object] = STATE(14),
    [sym_list] = STATE(14),
    [aux_sym_list_repeat1] = STATE(3),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_tok_identifier] = ACTIONS(7),
    [sym_tok_string] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_comment] = STATE(3),
    [sym_tok_code_block] = STATE(13),
    [sym_fragment] = STATE(17),
    [sym_string] = STATE(14),
    [sym_code_block] = STATE(14),
    [sym_recipe_ref] = STATE(14),
    [sym_object] = STATE(14),
    [sym_list] = STATE(14),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_tok_identifier] = ACTIONS(7),
    [sym_tok_string] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym_comment] = STATE(4),
    [sym_tok_code_block] = STATE(13),
    [sym_fragment] = STATE(17),
    [sym_string] = STATE(14),
    [sym_code_block] = STATE(14),
    [sym_recipe_ref] = STATE(14),
    [sym_object] = STATE(14),
    [sym_list] = STATE(14),
    [aux_sym_list_repeat1] = STATE(4),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [sym_tok_identifier] = ACTIONS(23),
    [sym_tok_string] = ACTIONS(26),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(32),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(38),
    [anon_sym_RBRACK] = ACTIONS(41),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_tok_identifier,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(11), 1,
      sym_tok_string,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    STATE(5), 1,
      sym_comment,
    STATE(13), 1,
      sym_tok_code_block,
    STATE(22), 1,
      sym_fragment,
    STATE(14), 5,
      sym_string,
      sym_code_block,
      sym_recipe_ref,
      sym_object,
      sym_list,
  [38] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(6), 1,
      sym_comment,
    ACTIONS(43), 10,
      ts_builtin_sym_end,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [57] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(7), 1,
      sym_comment,
    ACTIONS(45), 10,
      ts_builtin_sym_end,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [76] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(8), 1,
      sym_comment,
    ACTIONS(47), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [94] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(9), 1,
      sym_comment,
    ACTIONS(49), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [112] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(10), 1,
      sym_comment,
    ACTIONS(51), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [130] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(11), 1,
      sym_comment,
    ACTIONS(53), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [148] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(55), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [166] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(57), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [184] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(59), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [202] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(61), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [220] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(63), 9,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [238] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      sym_comment,
    ACTIONS(65), 7,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [257] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(41), 7,
      sym_tok_identifier,
      sym_tok_string,
      anon_sym_LT,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [273] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      sym_tok_identifier,
    ACTIONS(74), 1,
      anon_sym_STAR,
    STATE(29), 1,
      sym_recipe_ref,
    STATE(19), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [293] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(7), 1,
      sym_tok_identifier,
    ACTIONS(9), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(20), 1,
      sym_comment,
    STATE(29), 1,
      sym_recipe_ref,
  [315] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(79), 1,
      sym_tok_identifier,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(21), 2,
      sym_comment,
      aux_sym_object_repeat1,
  [329] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      sym_comment,
    ACTIONS(84), 2,
      sym_tok_identifier,
      anon_sym_RBRACE,
  [343] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(88), 1,
      sym_tok_identifier,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_object_repeat1,
    STATE(23), 1,
      sym_comment,
  [359] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(92), 1,
      sym_close_tag,
    ACTIONS(94), 1,
      sym_code,
    STATE(24), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_tok_code_block_repeat1,
  [375] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(94), 1,
      sym_code,
    ACTIONS(96), 1,
      sym_close_tag,
    STATE(24), 1,
      aux_sym_tok_code_block_repeat1,
    STATE(25), 1,
      sym_comment,
  [391] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(88), 1,
      sym_tok_identifier,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym_object_repeat1,
    STATE(26), 1,
      sym_comment,
  [407] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      sym_tok_identifier,
      anon_sym_STAR,
  [419] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(100), 1,
      sym_close_tag,
    ACTIONS(102), 1,
      sym_code,
    STATE(28), 2,
      sym_comment,
      aux_sym_tok_code_block_repeat1,
  [433] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_object,
    STATE(29), 1,
      sym_comment,
  [446] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(105), 2,
      sym_tok_identifier,
      anon_sym_RBRACE,
  [457] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(107), 2,
      sym_close_tag,
      sym_code,
  [468] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(109), 1,
      anon_sym_GT,
    STATE(32), 1,
      sym_comment,
  [478] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(111), 1,
      anon_sym_SLASH,
    STATE(33), 1,
      sym_comment,
  [488] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(113), 1,
      sym_tok_identifier,
    STATE(34), 1,
      sym_comment,
  [498] = 3,
    ACTIONS(115), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(117), 1,
      aux_sym_tok_code_block_token1,
    STATE(35), 1,
      sym_comment,
  [508] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(119), 1,
      sym_tok_identifier,
    STATE(36), 1,
      sym_comment,
  [518] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_COLON,
    STATE(37), 1,
      sym_comment,
  [528] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    STATE(38), 1,
      sym_comment,
  [538] = 3,
    ACTIONS(115), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(125), 1,
      aux_sym_comment_token1,
    STATE(39), 1,
      sym_comment,
  [548] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      sym_comment,
  [558] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(129), 1,
      sym_tok_identifier,
    STATE(41), 1,
      sym_comment,
  [568] = 1,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 38,
  [SMALL_STATE(7)] = 57,
  [SMALL_STATE(8)] = 76,
  [SMALL_STATE(9)] = 94,
  [SMALL_STATE(10)] = 112,
  [SMALL_STATE(11)] = 130,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 166,
  [SMALL_STATE(14)] = 184,
  [SMALL_STATE(15)] = 202,
  [SMALL_STATE(16)] = 220,
  [SMALL_STATE(17)] = 238,
  [SMALL_STATE(18)] = 257,
  [SMALL_STATE(19)] = 273,
  [SMALL_STATE(20)] = 293,
  [SMALL_STATE(21)] = 315,
  [SMALL_STATE(22)] = 329,
  [SMALL_STATE(23)] = 343,
  [SMALL_STATE(24)] = 359,
  [SMALL_STATE(25)] = 375,
  [SMALL_STATE(26)] = 391,
  [SMALL_STATE(27)] = 407,
  [SMALL_STATE(28)] = 419,
  [SMALL_STATE(29)] = 433,
  [SMALL_STATE(30)] = 446,
  [SMALL_STATE(31)] = 457,
  [SMALL_STATE(32)] = 468,
  [SMALL_STATE(33)] = 478,
  [SMALL_STATE(34)] = 488,
  [SMALL_STATE(35)] = 498,
  [SMALL_STATE(36)] = 508,
  [SMALL_STATE(37)] = 518,
  [SMALL_STATE(38)] = 528,
  [SMALL_STATE(39)] = 538,
  [SMALL_STATE(40)] = 548,
  [SMALL_STATE(41)] = 558,
  [SMALL_STATE(42)] = 568,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_ref, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_ref, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tok_code_block, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tok_code_block, 5, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tok_code_block_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tok_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tok_code_block_repeat1, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_close_tag = 0,
  ts_external_token_code = 1,
  ts_external_token_error_sentinel = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_close_tag] = sym_close_tag,
  [ts_external_token_code] = sym_code,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_close_tag] = true,
    [ts_external_token_code] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_close_tag] = true,
    [ts_external_token_code] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_chariot_external_scanner_create(void);
void tree_sitter_chariot_external_scanner_destroy(void *);
bool tree_sitter_chariot_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_chariot_external_scanner_serialize(void *, char *);
void tree_sitter_chariot_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_chariot(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_chariot_external_scanner_create,
      tree_sitter_chariot_external_scanner_destroy,
      tree_sitter_chariot_external_scanner_scan,
      tree_sitter_chariot_external_scanner_serialize,
      tree_sitter_chariot_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "chariot",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
